appName: grid-admin-api
nameSuffix: stage
forReal: false

timezone: Asia/Riyadh
lang: en_US.UTF-8

replicas: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

registryHost: me-riyadh-1.ocir.io
registryProjectName: axlo4g31gl45

spring:
  image:
    name: grid-admin-api-stage
    tag: main
    pullPolicy: Always
  containerPort: 8081
  service:
    port: 80
    type: LoadBalancer
  profile: stage
  javaOpts: "-Xms512m -Xmx1536m"
  pinpointEnabled: true
  pinpointSampleRate: 1
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi

db:
  url: "jdbc:postgresql://primary.djwsqwtfw5ivze7a4ch7hmvr4aseja.postgresql.me-riyadh-1.oci.oraclecloud.com:5432/gridadmindb"
  username: "gridadminappo"
  # password: injected from OCI Vault via secretProviderClass

backstage:
  signatureEnabled: "false"
  hostSecurityKey: "<BACKSTAGE_HOST_SECURITY_KEY>"  # TODO: fill in actual key

secretProviderClass:
  enabled: true
  vaultId: "ocid1.vault.oc1.me-riyadh-1.s5uu4gxoaade4.abqwuljr4pemf4omoa7bezmlcy2zcjzvbv5x22nwsvv4ouk7n2k5x2ggolaq"
  dbPasswordSecretName: "grid-admin-stage-db-passwd"

logging:
  # OCI Logging project OCID from PE team — dots replaced with __ (double underscore)
  # e.g. ocid1.log.me-riyadh-1.xxxx → ocid1__log__me-riyadh-1__xxxx
  ociLogOcid: "ocid1__log__oc1__me-riyadh-1__amaaaaaavimdcvyaybutcl5lsbuhzzpw4rn4ru543oxfh4pwjbm7ucacioba"

sidecar:
  name: wasl-proxy-sidecar
  image: me-riyadh-1.ocir.io/axlo4g31gl45/wasl-sidecar-proxy:260114-1913

imagePullSecrets: "mapservice-ocir-read"

nodeSelector:
  kubernetes.io/arch: amd64

ncc:
  application: grid-admin-api
  instance: grid-admin-api
  version: 1
  installation: 2026-0101-0001  # TODO: update to actual installation ID
